name: bootanimation_maker
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  archive: ^3.6.1
  ffmpeg_kit_flutter: ^6.0.3
  file_picker: ^8.1.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get: any
  intl: any
  path_provider: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  generate: true
